# Generated by Django 5.1.5 on 2025-01-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_audiofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(upload_to='audio/'),
        ),
    ]
